# Site settings
title: Arman Shafiei
description: 'Github Page'
url: 'https://arman-shafiei.github.io/about'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Arman Shafiei'
  email: armanshafeie77@gmail.com
  #    twitter_username: thomzuehlke
  #    facebook_username: joshgerdes
  github_username:  arman-shafiei
  linkedin_username: armanshafeie77@gmail.com
  #  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
