# Your Website Title
title: Arman Shafiei

# Your Website URL
url: 'https://info.arman-projects.com'

# Leave it default
baseurl: 'https://info.arman-projects.com/' 

# Google Analytics
#ga_index: UA-XXXXXXXX-X
#ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Arman Shafiei
tagline: DevOps & Linux Engineer
pic: profile.jpeg # profile.png can be found at /assets/images/profile.png
description: DevOps & Linux Engineer
#description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: arman.shafiei.1998@gmail.com
website: info.arman-projects.com # do not add http://
linkedin: arman-shafiei
github: arman-shafiei
#twitter: '@realmelvinchng'
#facebook:
medium: '@armanshafiei98'


# Files or folders to be excluded
#exclude: gitbook/

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
