# Your Website Title
title: Arman Shafiei

# Your Website URL
url: 'https://arman-shafiei.github.io/about'

# Leave it default
baseurl: '' 

# Google Analytics
#ga_index: UA-XXXXXXXX-X
#ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Arman Shafiei
tagline: DevOps Engineer
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: DevOps Engineer
#description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: armanshafeie77@gmail.com
website: arman-shafiei.github.io # do not add http://
linkedin: armanshafeie77@gmail.com
github: arman-shafiei
#twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
